server:
  port: 8080
  servlet:
    context-path: /transportbooking


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/transportbooking"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer-key: "a8c52ea7607393929dd1d393d0a0519879fbf22b28e10b4b9f5b91fbfb4db051"